### ISSUE TITLE
Git-phlow should support zenhub

### ISSUE THREAD

**Issue by lakruzz** [devx-cafe/git-phlow#312]
Implement support for automated transition btw lists in ZenHub.

Currently it's based on Labels, and a certain configuration in Waffle - But:

> _"Waffle's dead babe, Waffle's dead!"_

**Comment by groenborg** [comment]
Does ZenHub use labels to move tasks between boards like Waffle? or do they have a different mechanism for automatic task management?  
They have a well-documented API so it should be straight forward to add support for this. 
https://github.com/ZenHubIO/API#move-an-issue-between-pipelines

**Comment by lakruzz** [comment]
They don't support labels (like Waffle) so we will have to trigger it through the API

**Comment by lakruzz** [comment]
We're already using the Zenhub API for other stuff, so I think the biggest hurdle is to 

- Setup the dev environment for go-lang
- the development itself should not be difficult
- But we don't know the condition of the pipeline/test
- Deployment?
- Release?

@groenborg It could be fun to set up a CodeCamp with you, and get all of this up to speed again, so we can take Git-Phlow to the next level!

**Comment by groenborg** [comment]
@lakruzz yes it could and will be. My Golang is a little "Rust"y ;) but I will get up to speed in no time. I have tons of ideas for improvement, but first and foremost we should get the pipeline back up. No development without proper CI.  
The biggest shortcoming of Go was its very limited functionality for handling dependencies, this issue now seems to have been fixed in Go 1.8 or 1.9, so setting up the dev env should be a much simpler task!
